---
apiVersion: v1
kind: Secret
metadata:
  name: git-application
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/szabos/application.git
  username: username
  password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: img-docker
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: docker.io/steveszabo/webapp
  username: username
  password: password
